### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by josruirod** [NUStatBioinfo/DegNorm#23]
Hi,
Thank you for your development. 
I have tried to use your program in a shared cluster but I'm finding that at some steps it seem to ignore the -p argument and use all the available resources, particularly in the iterations.
In my circumstances, this behaviour makes not possible to use it right now. Do you have any comment? Could this be fixed?

Thank you

**Comment by ffineis** [comment]
Hello, thx for using DegNorm. Sure, I'll look into it and get back to you soon.

**Comment by ffineis** [comment]
I made the following changes in https://github.com/NUStatBioinfo/DegNorm/pull/24, it updates the default number of threads to 1 (changed from max available resources - 1). Pull updates from master and reinstall?

That said, you will need the ability to run at least 2 concurrent processes because we call the `subprocess` module and launch subprocesses to do things like check for the availability of certain software, using `samtools`, and using `pandoc`.

**Comment by josruirod** [comment]
Ok great, thanks for your support. Yes, no problem with using 2 or more threads, but I cannot use all of them. I'll test it and let you know if something is not working.

Thanks

**Comment by ffineis** [comment]
Wondering if this issue is resolved? Can we close out?

**Comment by josruirod** [comment]
Yes it can be closed.
Thanks for the support
